-keep class ch.rmy.android.http_shortcuts.data.models.** { *; }
-keep class ch.rmy.android.http_shortcuts.data.realm.models.** { *; }
-keep class ch.rmy.android.http_shortcuts.import_export.models.** { *; }
-keep class ch.rmy.android.http_shortcuts.activities.contact.MetaData { *; }
-keep class ch.rmy.android.http_shortcuts.activities.execute.models.ExecutionParams { *; }
-keep class ch.rmy.android.http_shortcuts.http.FileUploadManager$Result { *; }
-keep class ch.rmy.android.http_shortcuts.http.FileUploadManager$File { *; }
-keep class ch.rmy.android.http_shortcuts.http.HttpRequesterWorker$Params { *; }
-keep class ch.rmy.android.http_shortcuts.history.HistoryEvent$ShortcutTriggered { *; }
-keep class ch.rmy.android.http_shortcuts.history.HistoryEvent$ShortcutCancelled { *; }
-keep class ch.rmy.android.http_shortcuts.history.HistoryEvent$HttpRequestSent { *; }
-keep class ch.rmy.android.http_shortcuts.history.HistoryEvent$HttpResponseReceived { *; }
-keep class ch.rmy.android.http_shortcuts.history.HistoryEvent$NetworkError { *; }
-keep class ch.rmy.android.http_shortcuts.history.HistoryEvent$Error { *; }
-keep class ch.rmy.android.http_shortcuts.history.HistoryEvent$CustomEvent { *; }
-dontwarn com.yalantis.ucrop**
-keep class com.yalantis.ucrop** { *; }
-keep interface com.yalantis.ucrop** { *; }
-keep class com.joaomgcd.taskerpluginlibrary.** { *; }
-keep class net.dinglisch.android.tasker.** { *; }
-keep class androidx.compose.material3.TabRowKt { *; } # here because I had to resort to reflection to change a hard-coded value
-dontwarn org.apache.harmony.xnet.provider.jsse.SSLParametersImpl
-dontwarn org.bouncycastle.jsse.BCSSLParameters
-dontwarn org.bouncycastle.jsse.BCSSLSocket
-dontwarn org.bouncycastle.jsse.provider.BouncyCastleJsseProvider
-dontwarn org.openjsse.javax.net.ssl.SSLParameters
-dontwarn org.openjsse.javax.net.ssl.SSLSocket
-dontwarn org.openjsse.net.ssl.OpenJSSE

-keep class androidx.room.RoomDatabase { *; }
-keep class androidx.room.Room { *; }
-keep class android.arch.** { *; }
-keep @androidx.room.Entity class *
-dontwarn androidx.room.paging.**