-keep class org.liquidplayer.javascript.** { *; }
-keep class ch.rmy.android.http_shortcuts.data.models.** { *; }
-keep class ch.rmy.android.http_shortcuts.activities.contact.MetaData { *; }
-dontwarn com.yalantis.ucrop**
-keep class com.yalantis.ucrop** { *; }
-keep interface com.yalantis.ucrop** { *; }
-keep class com.joaomgcd.taskerpluginlibrary.** { *; }
-keep class net.dinglisch.android.tasker.** { *; }